# Meta
title: "Cafe Züfle Baiersbronn-Mitteltal"
author: "Felix Pojtinger"
email: "felix@pojtinger.com"
lang: "de"
description: >-
  Static site for Cafe Züfle in Baiersbronn-Mitteltal.
keywords:
  - "Cafe Zuefle"

# Contact
contact:
  phone: "07442 / 81320"
  email: "cafe-m.zuefle@t-online.de"
  website: "cafe-zuefle.de"

# Location
location:
  address: "Ruhesteinstr. 304-307, 72270 Baiersbronn-Mitteltal"
  iframe_url: "https://www.google.com/maps/embed/v1/place?q=Ruhesteinstr.+304-307,+72270+Baiersbronn-Mitteltal&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"

# Config
baseurl: ""
url: "https://cafe-zuefle.de"
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
collections:
  pages:
    output: true
    permalink: /:path.html

# Plugins
plugins:
  - "jekyll-admin"
  - "jekyll-sitemap"
  - "jekyll-last-modified-at"
  - "jekyll-assets"
  - "jekyll-gzip"

# Decentralized Admin Interface
jekyll_admin:
  hidden_links:
    - posts # We don't have any posts currently
    - datafiles # We don't have any data files yet
