apiVersion: apps/v1
kind: Deployment
metadata:
  name: pension-cafe-baeckerei-zuefle-site
spec:
  selector:
    matchLabels:
      app: pension-cafe-baeckerei-zuefle-site
  template:
    metadata:
      labels:
        app: pension-cafe-baeckerei-zuefle-site
    spec:
      containers:
        - name: pension-cafe-baeckerei-zuefle-site
          image: registry.gitlab.com/pojntfx/pension-cafe-baeckerei-zuefle-site
          resources:
            limits:
              memory: 400Mi
              cpu: 400m
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: pension-cafe-baeckerei-zuefle-site
spec:
  type: NodePort
  selector:
    app: pension-cafe-baeckerei-zuefle-site
  ports:
    - port: 4000
      nodePort: 30300
