backend:
  name: "git-gateway"
media_folder: "img"
collections:
  - name: "pages"
    label: "Pages"
    folder: ""
    create: false
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "default"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"