backend:
  name: "git-gateway"
media_folder: "img"
collections:
  - name: "page"
    label: "Page"
    folder: "_pages"
    create: false
    slug: ".md"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["default", "home"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}