backend:
  name: "git-gateway"
media_folder: "img"
collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: false
    slug: ".md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "select"
        options:
          - "home"
          - "default"
        default: "default"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"